### PR TITLE
Correctly parse table elements initialized to imported functions

### LINKED ISSUE #151: twiggy crashes with mono binaries
Hello,

I'm trying to use twiggy 0.2.0 with mono's wasm port and hitting this crash on OSX:

```
tijuca:wasm rokumper$ RUST_BACKTRACE=1 twiggy top debug/mono.wasm
thread 'main' panicked at 'assertion failed: index < u32::MAX as usize', /Users/kumpera/.cargo/registry/src/github.com-1ecc6299db9ec823/twiggy-ir-0.2.0/./ir.rs:414:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: twiggy_ir::Id::entry
   7: twiggy_parser::wasm::<impl twiggy_parser::Parse<'a> for parity_wasm::elements::section::ElementSection>::parse_edges
   8: twiggy_parser::wasm::<impl twiggy_parser::Parse<'a> for parity_wasm::elements::module::Module>::parse_edges
   9: twiggy_parser::parse_wasm
  10: twiggy_parser::read_and_parse
  11: twiggy::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
```

To reproduce it. Download this file: https://jenkins.mono-project.com/job/test-mono-mainline-wasm/926/label=ubuntu-1804-amd64/Azure/processDownloadRequest/926/ubuntu-1804-amd64/sdks/wasm/mono-wasm-24c1f2a40c1.zip

Then run twiggy: `twiggy top debug/mono.wasm`

### PR DESCRIPTION
**Pull request by fitzgen**
We were previously assuming that all table elements were initialized to functions defined locally. If we encountered a table element initialized to an imported function, we attempted to subtract the number of imported functions from it, and that would cause a subtraction underflow.

Fixes #151

### CODE REVIEW

File: parser/wasm_parse/mod.rs [hunk 1]
```diff
@@ -541,31 +541,47 @@ impl<'a> Parse<'a> for elements::ElementSection {
...
+                // against the number of imported functions to determine
+                // which we are dealing with.
+                if func_idx < num_imported_funcs as u32 {
+                    // Add an edge to the function import.
+                    if let Some(import_section_idx) = import_section_idx {
+                        let import_id = Id::entry(import_section_idx, func_idx as usize);
+                        items.add_edge(elem_id, import_id);
+                    }
+                } else {
+                    // Add an edge to the
```
Comment (data-pup) [inline parser/wasm_parse/mod.rs]: Nit: this comment is just a sentence fragment

**Comment by data-pup** [comment]
r+me, aside from the nitpick above regarding that comment :+1: Looks great to me!

File: parser/wasm_parse/mod.rs (hunk 1 above)
Comment (fitzgen) [reply parser/wasm_parse/mod.rs]: D'oh -- thanks for catching that :-p

**Comment by fitzgen** [comment]
Thanks @data-pup :)
